#!/bin/bash

source bashlib.bashrc # Импорт общих функций и переменнх

ip=$1
app=$2
server_name=$3


while [[ -z "$ip" ]]; do 
  printf "ip адрес веб сервера на который будет установлено приложение: " 
  read ip
done

while [[ -z "$app" ]]; do
  printf "Название веб приложения (подпапки в /var/www/): " 
  read app
done

while [[ -z "$server_name" ]]; do
  printf "server_name (например $YELLOW$app.example.com$NOCOLOR): " 
  read server_name
done

ansible-playbook -i webasyst-servers.ini --limit=$ip install-webasyst.yml \
  --extra-vars app="$app" \
  --extra-vars server_name="$server_name" 
