#!/bin/bash

ip=$1
app=$2
echo TODO:
echo [mysqld]
echo default_authentication_plugin = mysql_native_password
echo validate_password.policy=1
echo validate_password.length=1
echo validate_password.number_count=0
echo validate_password.mixed_case_count=0
echo validate_password.special_char_count=0
echo validate_password.check_user_name=1
echo skip-log-bin

if [ -z "$app" ]; then
  echo "installwa ip app"
  echo "  ip - адрес веб сервера из списка в ini файле webasyst-servers.ini"
  echo "  app - название приложения (используется как папка webasys, бд mysql, пользователь mysql с правами для этой БД"
  exit
fi
ansible-playbook -i webasyst-servers.ini --limit=$ip --extra-vars app=$app install-webasyst.yml